site_name: Plant Gene Expression Uploader
theme:
  name: material
  palette:
    primary: blue grey
    accent: teal
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant  # XHR instant reloading
    - navigation.tracking  # Anchor tracking
    # - navigation.indexes  # Sections are also pages
    - navigation.top  # Back to top
    - navigation.expand  # Expand collapsible subsections by default
    - toc.follow  # Sponsor only (not working)
    - content.code.annotate
    - search.highlight  # For highlighing search results

# Order the pages on navigation here
nav:
  - Overview: index.md
  - Data:
    - data-processing/index.md
    - Expression matrices: data-processing/tpm_matrices.md
    - Plant Ontology annotations: data-processing/po_annotations.md
    - Protein sequences: data-processing/protein_sequences.md
    - Mapman annotations: data-processing/mapman_annotations.md
  - Using the uploader:
    - uploading/index.md
    - Setup repository: uploading/setup.md
    - Reader classes: uploading/readers.md
    - Uploading steps: uploading/uploading_steps.md
  # - Data preprocessing: data_preprocessing.md
  - Database:
    - Database schema: db/schema.md
    - MongoDB hosting: db/db_hosting.md
  - Other components:
    - Protein sequence search: components/diamond_search.md
    - Front-end repository: components/front_end.md

repo_url: https://github.com/wirriamm/omnibus-uploader-2
repo_name: wirriamm/omnibus-uploader-2
copyright: Mutwil Lab 2022
extra:
  generator: false  # Made with Material for MkDocs
  social:
    - icon: material/web
      link: https://plant.tools

markdown_extensions:
  # Lists
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Others
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Text formatting
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # Tables
  - tables
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # Definition lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
