site_name: Plant Gene Expression Uploader
theme:
  name: material
  palette:
    primary: blue grey
    accent: teal
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant  # XHR instant reloading
    - navigation.tracking  # Anchor tracking
    - navigation.indexes  # Sections are also pages
    - navigation.top  # Back to top
    - toc.follow  # Sponsor only (not working)
    - content.code.annotate

# Order the pages on navigation here
nav:
  - Overview: index.md
  - Setup repository: setup.md
  - Data preprocessing: data_preprocessing.md
  - Reader classes: readers.md
  - Uploading steps: uploading.md

repo_url: https://github.com/wirriamm/omnibus-uploader-2
repo_name: wirriamm/omnibus-uploader-2
copyright: Mutwil Lab 2022
extra:
  generator: true
  social:
    - icon: material/web
      link: https://plant.tools

markdown_extensions:
  # Lists
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Others
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Text formatting
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  # Tables
  - tables
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # Definition lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
